image: davesilva/docker-experimental:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- davesilva/docker-experimental:dind

before_script:
- docker info
- mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

build-projector-arm: &build-job-arm
  tags:
    - arm
    - docker
  variables:
    IMAGE: davesilva/home-automation-projector
    DOCKER_CONTEXT: projector
    OS_ARCH: linux-arm-v7
  stage: build
  script:
  - docker pull $IMAGE:latest-$OS_ARCH || true
  - |
    docker build --cache-from $IMAGE:latest \
                 --tag $IMAGE:$CI_BUILD_REF-$OS_ARCH \
                 --tag $IMAGE:latest-$OS_ARCH $DOCKER_CONTEXT
  - docker push $IMAGE:$CI_BUILD_REF-$OS_ARCH
  - docker push $IMAGE:latest-$OS_ARCH

build-volume-arm:
  <<: *build-job-arm
  variables:
    IMAGE: davesilva/home-automation-volume
    DOCKER_CONTEXT: volume
    OS_ARCH: linux-arm-v7

build-web-arm:
  <<: *build-job-arm
  variables:
    IMAGE: davesilva/home-automation-web
    DOCKER_CONTEXT: web
    OS_ARCH: linux-arm-v7

build-snips-action-handlers-arm:
  <<: *build-job-arm
  variables:
    IMAGE: davesilva/home-automation-snips-action-handlers
    DOCKER_CONTEXT: snips-action-handlers
    OS_ARCH: linux-arm-v7

build-mosquitto-arm:
  <<: *build-job-arm
  variables:
    IMAGE: davesilva/home-automation-mosquitto
    DOCKER_CONTEXT: mosquitto
    OS_ARCH: linux-arm-v7

build-projector-amd64: &build-job-amd64
  <<: *build-job-arm
  tags:
    - shared
    - docker
  variables:
    IMAGE: davesilva/home-automation-projector
    DOCKER_CONTEXT: projector
    OS_ARCH: linux-amd64

build-volume-amd64:
  <<: *build-job-amd64
  variables:
    IMAGE: davesilva/home-automation-volume
    DOCKER_CONTEXT: volume
    OS_ARCH: linux-amd64

build-web-amd64:
  <<: *build-job-amd64
  variables:
    IMAGE: davesilva/home-automation-web
    DOCKER_CONTEXT: web
    OS_ARCH: linux-amd64

build-snips-action-handlers-amd64:
  <<: *build-job-amd64
  variables:
    IMAGE: davesilva/home-automation-snips-action-handlers
    DOCKER_CONTEXT: snips-action-handlers
    OS_ARCH: linux-amd64

build-mosquitto-amd64:
  <<: *build-job-amd64
  variables:
    IMAGE: davesilva/home-automation-mosquitto
    DOCKER_CONTEXT: mosquitto
    OS_ARCH: linux-amd64
