image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info
- mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

build-projector: &build-job
  tags:
    - arm
    - docker
  variables:
    IMAGE: davesilva/home-automation-projector
    DOCKER_CONTEXT: projector
    OS_ARCH: linux-arm-v7
  stage: build
  script:
  - docker pull $IMAGE:latest-$OS_ARCH || true
  - |
    docker build --cache-from $IMAGE:latest \
                 --tag $IMAGE:$CI_BUILD_REF-$OS_ARCH \
                 --tag $IMAGE:latest-$OS_ARCH $DOCKER_CONTEXT
  - docker push $IMAGE:$CI_BUILD_REF-$OS_ARCH
  - docker push $IMAGE:latest-$OS_ARCH

build-volume:
  <<: *build-job
  variables:
    IMAGE: davesilva/home-automation-volume
    DOCKER_CONTEXT: volume
    OS_ARCH: linux-arm-v7

build-web:
  <<: *build-job
  variables:
    IMAGE: davesilva/home-automation-web
    DOCKER_CONTEXT: web
    OS_ARCH: linux-arm-v7

build-snips-action-handlers:
  <<: *build-job
  variables:
    IMAGE: davesilva/home-automation-snips-action-handlers
    DOCKER_CONTEXT: snips-action-handlers
    OS_ARCH: linux-arm-v7

build-mosquitto:
  <<: *build-job
  variables:
    IMAGE: davesilva/home-automation-mosquitto
    DOCKER_CONTEXT: mosquitto
    OS_ARCH: linux-arm-v7
