image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build-projector:
  stage: build
  script:
  - docker build -t davesilva/home-automation-projector:1.0.2 projector
