apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: davesilva/mosquitto:2.0.11
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: mosquitto-persistence
          mountPath: /mosquitto/data
      volumes:
      - name: mosquitto-persistence
        persistentVolumeClaim:
          claimName: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-nodeport
  namespace: home-automation
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
  - name: mosquitto-mqtt
    port: 1883
  - name: mosquitto-websocket
    port: 9001
  externalIPs: ["192.168.1.8"]
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.4
  selector:
    app: mosquitto
  ports:
  - name: mosquitto-mqtt
    port: 1883
  - name: mosquitto-websocket
    port: 9001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
