apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: davesilva/mosquitto:2.0.14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: mosquitto-persistence
          mountPath: /mosquitto/data
        resources:
          requests:
            cpu: 0.1
            memory: 40Mi
          limits:
            cpu: 0.1
            memory: 40Mi
      volumes:
      - name: mosquitto-persistence
        persistentVolumeClaim:
          claimName: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: mosquitto
  ports:
  - name: mosquitto-mqtt
    port: 1883
  - name: mosquitto-websocket
    port: 9001
  loadBalancerIP: 192.168.1.16
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
