apiVersion: apps/v1
kind: Deployment
metadata:
  name: projector-mqtt-bridge
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projector-mqtt-bridge
  template:
    metadata:
      labels:
        app: projector-mqtt-bridge
    spec:
      containers:
      - name: projector-mqtt-bridge
        image: davesilva/home-automation-projector:1.2.1
        imagePullPolicy: IfNotPresent
        env:
        - name: PROJECTOR_HOST
          value: 192.168.1.11
        - name: BROKER_HOST
          value: mosquitto
        resources:
          requests:
            cpu: 0.1
            memory: 20Mi
          limits:
            cpu: 0.1
            memory: 20Mi
