apiVersion: apps/v1
kind: Deployment
metadata:
  name: projector-mqtt-bridge
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projector-mqtt-bridge
  template:
    metadata:
      labels:
        app: projector-mqtt-bridge
    spec:
      containers:
      - name: projector-mqtt-bridge
        image: davesilva/home-automation-projector:1.2.0
        imagePullPolicy: Always
        env:
        - name: PROJECTOR_HOST
          value: E91D031A.hosts.dmsilva.com
        - name: BROKER_HOST
          value: mosquitto
