apiVersion: apps/v1
kind: Deployment
metadata:
  name: snips-action-handlers
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snips-action-handlers
  template:
    metadata:
      labels:
        app: snips-action-handlers
    spec:
      containers:
      - name: snips-action-handlers
        image: davesilva/home-automation-snips-action-handlers:2.2.0
        imagePullPolicy: Always
        env:
        - name: BROKER_HOST
          value: mosquitto
