apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: home-automation
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: davesilva/home-automation-web:1.6.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0.01
            memory: 10Mi
          limits:
            cpu: 0.01
            memory: 10Mi
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: home-automation
spec:
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: home-automation
spec:
  rules:
  - host: volume.home.dmsilva.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              name: http
  - host: volume.xxx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              name: http
