apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: home-automation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: davesilva/home-automation-web:1.0.0
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: home-automation
spec:
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 192.168.1.8
